# Generated by Django 4.2.7 on 2026-05-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumniprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
