# Generated by Django 4.2.7 on 2026-05-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0002_alumniprofile_bio_alumniprofile_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumniprofile",
            name="current_city",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
