# Generated by Django 5.2.13 on 2026-05-02 16:25

import alumni.storage_backends
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0003_alumniprofile_current_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("reunion", "Reunion"),
                            ("webinar", "Webinar"),
                            ("sports", "Sports"),
                            ("cultural", "Cultural"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "event_date",
                    models.DateTimeField(help_text="Event start date and time (IST)"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional end date/time for multi-day events",
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=300)),
                ("is_online", models.BooleanField(default=False)),
                (
                    "online_link",
                    models.URLField(blank=True, help_text="Google Meet / Zoom link"),
                ),
                (
                    "max_attendees",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave blank for unlimited capacity",
                        null=True,
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="0.00 means free event",
                        max_digits=8,
                    ),
                ),
                ("fee_currency", models.CharField(default="INR", max_length=5)),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        help_text="Event poster image (JPG / WebP / GIF). GIF animates in app.",
                        null=True,
                        storage=alumni.storage_backends.EventBannerStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "banner_video",
                    models.FileField(
                        blank=True,
                        help_text="Optional looping video header (MP4 / WebM, max ~50 MB).",
                        null=True,
                        storage=alumni.storage_backends.EventVideoStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Only published events are visible in the app",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["event_date"],
            },
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("attending", "Attending"),
                            ("not_attending", "Not Attending"),
                            ("maybe", "Maybe"),
                        ],
                        default="attending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not Required"),
                            ("pending", "Payment Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="not_required",
                        max_length=20,
                    ),
                ),
                (
                    "payment_ref",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay order/payment ID — populated after payment integration",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="e.g. 'Bringing +1'")),
                ("rsvp_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="alumni.event",
                    ),
                ),
            ],
            options={
                "ordering": ["rsvp_at"],
                "unique_together": {("event", "alumni")},
            },
        ),
    ]
