# Generated by Django 5.2.13 on 2026-05-12 18:12

from django.db import migrations


def migrate_stackable_data(apps, schema_editor):
    AlumniProfile = apps.get_model('alumni', 'AlumniProfile')
    WorkExperience = apps.get_model('alumni', 'WorkExperience')
    Education = apps.get_model('alumni', 'Education')

    for profile in AlumniProfile.objects.all():
        # Migrate 10+2 Stream
        if profile.edu_10_plus_2_stream:
            stream_label = dict(profile._meta.get_field('edu_10_plus_2_stream').choices).get(profile.edu_10_plus_2_stream, profile.edu_10_plus_2_stream)
            Education.objects.create(
                profile=profile,
                degree="10+2",
                field_of_study=stream_label,
                institution_name="High School (Migrated)",
            )
        
        # Migrate Graduation
        if profile.edu_graduation_course or profile.edu_graduation_college or profile.edu_graduation_university:
            Education.objects.create(
                profile=profile,
                degree=profile.edu_graduation_course or "Graduation",
                institution_name=profile.edu_graduation_college or profile.edu_graduation_university or "University",
            )
        
        # Migrate Post-Graduation
        if profile.edu_postgrad_degree or profile.edu_postgrad_college or profile.edu_postgrad_university:
            Education.objects.create(
                profile=profile,
                degree=profile.edu_postgrad_degree or "Post-Graduation",
                institution_name=profile.edu_postgrad_college or profile.edu_postgrad_university or "University",
            )
        
        # Migrate Work Experience
        if profile.current_company or profile.designation or profile.current_role:
            WorkExperience.objects.create(
                profile=profile,
                company_name=profile.current_company or "Unknown Company",
                designation=profile.designation or profile.current_role or "Professional",
                description=profile.business_details or "",
                is_current=True
            )


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_alter_alumniprofile_options_education_workexperience'),
    ]

    operations = [
        migrations.RunPython(migrate_stackable_data, reverse_migration),
    ]
