# Generated by Django 5.2.13 on 2026-05-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_migrate_stackable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniprofile',
            name='business_details',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='current_company',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='current_role',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='edu_10_plus_2_stream',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='edu_graduation_college',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='edu_graduation_course',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='edu_graduation_university',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='edu_postgrad_college',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='edu_postgrad_degree',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='edu_postgrad_university',
        ),
    ]
