# Generated by Django 5.2.13 on 2026-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_remove_alumniprofile_business_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumniprofile',
            options={'ordering': ['-batch', 'first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='graduation_year',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company_instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company_linkedin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company_website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
