"""
alumni/urls.py
Responsibility: URL routing for the alumni app.
"""

from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import AlumniProfileViewSet, EventListView, EventDetailView, RSVPView

# ── Existing profile routes (auto-generated by router) ──
router = DefaultRouter()
router.register(r"profiles", AlumniProfileViewSet, basename="alumni-profile")

# ── New event + RSVP routes ──
event_urlpatterns = [
    path("events/",          EventListView.as_view(),   name="event-list"),
    path("events/<int:pk>/", EventDetailView.as_view(), name="event-detail"),
    path("events/<int:pk>/rsvp/", RSVPView.as_view(),  name="event-rsvp"),
]

urlpatterns = router.urls + event_urlpatterns
